### ISSUE TITLE
fife need fifechan even if fifechan support disable

### ISSUE THREAD

**Issue by fiziologus** [fifengine/fifengine#1001]
fifechan files (FCHAN_SRC) use for build fife python extension.

**Comment by jakoch** [comment]
Thank you for the report. 
Adding FCHAN_SRC unconditionally is wrong. It needs to be wrapped into the fifechan condition.

Note for myself: [CMakeLists-master#L842](https://github.com/fifengine/fifengine/blob/a58c87b40cdb1f18fa3236156470f6c0b063362f/CMakeLists.txt#L842)

**Comment by jakoch** [comment]
@Beliaar You already solved this with the `FIFE_SOURCES` change, right?

**Comment by Beliaar** [comment]
Ah, yeah, i forget that this issue existed. It was fixed with commit 6d5e0d32f1d9a327550970ec600f87afe333e3dd.
