### ISSUE TITLE
[cmake] cmake_minimum_required version

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine#1003]
Hey!

I would like to raise the `cmake_minimum_required` version to `3.2.2`.
The last change here was a raise from `2.6` to `2.8.5`, see [here](https://github.com/fifengine/fifengine/commit/063f4e111624db75666760176e15e7cee31fe279#diff-af3b638bc2a3e6c650974192a53c7291R5).

I've checked our build services for the lowest common version. 

Here is the overview:

Travis-CI has

- CMake v3.2.2 on Linux (Trusty) - https://travis-ci.org/fifengine/fifengine/jobs/204838475#L935
- CMake v3.6.2 on Mac - https://travis-ci.org/fifengine/fifengine/jobs/204838477#L1012

Appveyor has

- CMake v3.7.2 on Win - https://ci.appveyor.com/project/LinuxDonald/fifengine/build/dev-a9ad8a6/job/tf1vcqd8mpkjpw1y#L7

Do we have to take any other build or packaging services (downstream) into account before raising?

CC @ignatenkobrain

**Comment by prock-fife** [comment]
I seem to remember some linux distros still using 2.6???

**Comment by LinuxDonald** [comment]
@prock-fife i dont think that. debian stable use 3.0 https://packages.debian.org/jessie/cmake
And if an linux distros have older packages then debian maybe its dead :D

**Comment by ignatenkobrain** [comment]
RHEL uses 2.8.11

**Comment by ignatenkobrain** [comment]
but who cares about that outdated thing ;)

**Comment by LinuxDonald** [comment]
ups :( yeah RHEL/CentOS but we cant support all linux distro. And RHEL/CentOS have an very long life cyle per version.
