### ISSUE TITLE
[cmake] finder OpenAL → OpenALSoft

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine#1005]
We currently use the official finder for OpenAL by running:

    find_package(OpenAL REQUIRED)

But we use OpenAL-Soft with a different installation location for the library!

Example-wise Mac:
- openal-soft is fetched, https://travis-ci.org/fifengine/fifengine/jobs/205339213#L41
- lands here: https://travis-ci.org/fifengine/fifengine/jobs/205339213#L996
- and then we use the official cmake finder: https://github.com/fifengine/fifengine/blob/master/CMakeLists.txt#L679
- which brings us to the question, which cmake version with which finder version we have.. https://github.com/Kitware/CMake/blob/master/Modules/FindOpenAL.cmake

---

- [x] create custom finder `FindOpenALSoft.cmake`
- [x] use `find_package(OpenALSoft REQUIRED)`

**Blocker**: for branch [audio_reworking](https://github.com/fifengine/fifengine/tree/audio_reworking)

**Comment by LinuxDonald** [comment]
fixed in master.
