### ISSUE TITLE
audio_tests.py broken

### ISSUE THREAD

**Issue by susnux** [fifengine/fifengine#1006]
audio_tests.py fails with "No module named fifelog".
I think this: `import time, fifelog`
has to be replaced with this: `from fife.extensions import fifelog`
(and the import for time).

Complete log:
> [  678s] ===== Running test_sharedptr =====
> [  678s] Using the FIFE python module found here:  /home/abuild/rpmbuild/BUILDROOT/fife-0.4.1-41.1.i386/usr/lib/python2.7/site-packages/fife
> [  678s] Traceback (most recent call last):
> [  678s]   File "./run_tests.py", line 225, in <module>
> [  678s]     main()
> [  678s]   File "./run_tests.py", line 219, in main
> [  678s]     run(options.automatic, args)
> [  678s]   File "./run_tests.py", line 204, in run
> [  678s]     run_all(alltests)
> [  678s]   File "./run_tests.py", line 104, in run_all
> [  678s]     swig_errors, swig_failures = run_test_modules(tests['swig'])
> [  678s]   File "./run_tests.py", line 83, in run_test_modules
> [  678s]     imported = get_dynamic_imports(modules)
> [  678s]   File "./run_tests.py", line 76, in get_dynamic_imports
> [  678s]     m = __import__(module)
> [  678s]   File "/home/abuild/rpmbuild/BUILD/fifengine-0.4.1/tests/swig_tests/audio_tests.py", line 26, in <module>
> [  678s]     import time, fifelog
> [  678s] ImportError: No module named fifelog

**Comment by helios2000** [comment]
Thank you for reporting the issue!

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/311a398bc59c19e093e428f6df0fb984c142713b
