### ISSUE TITLE
Render problems with SDL 2.0.5

### ISSUE THREAD

**Issue by helios2000** [fifengine/fifengine#1008]
The main camera is broken on rio de hola. Only the small camera is rendered correctly. If the small camera is disabled the main screen looks right again. So it could be that there is a problem with cliping planes.
Additonal some gui elements looks broken. No border lines and so on.

**Comment by LinuxDonald** [comment]
SDL 2.0.6 is out i will work on the next days on the new Windows SDK that use it.

**Comment by LinuxDonald** [comment]
New SDK is out: https://ci.appveyor.com/project/LinuxDonald/fife-windows-sdk/build/artifacts

**Comment by helios2000** [comment]
Does the problem still occur with 2.0.6? You can simple check it, change the backend setting from OpenGL to SDL and start rio de hola.
