### ISSUE TITLE
Uncoupled endif(build-python) in CMakeLists.txt

### ISSUE THREAD

**Issue by AndyMender** [fifengine/fifengine#1010]
As is, fifengine will not build from the python3_futurize branch as there is a loose `endif(build-python)` statement on line 811. Removing it fixes the problem.

**Comment by Beliaar** [comment]
hmm, let me check that, i am sure i did try to build after the merge.

**Comment by Beliaar** [comment]
oh... i somehow did not commit that change... one minute.

**Comment by AndyMender** [comment]
It runs fine. CMake completes the setup and the module is built.
