### ISSUE TITLE
Implement hardware image cursor

### ISSUE THREAD

**Issue by Niektory** [fifengine/fifengine#1012]
SDL2 supports setting an image to the hardware cursor via [SDL_CreateColorCursor()](https://wiki.libsdl.org/SDL_CreateColorCursor), which can replace our current software implementation.

Advantages:
- Much lower latency when VSync is on.
- Retains smooth movement when framerate is low or rendering stalls.

Limitations:
- The cursor might not show up on screenshots or videos.
- Only one image can be used, so the "drag cursor" would have to be combined with the main cursor into a single image or rendered in software.
- Some fancy stuff might not be possible. Not that we need anything fancy, but we might want to in the future.

~~Considering the above, is it fine to replace the software cursor completely or do we want to have both options?~~
Scratch that, we definitely want to have both.

**Comment by helios2000** [comment]
Ok as an additional cursor option. Do you want to implement it?

**Comment by Niektory** [comment]
Yeah I think I'll give this a shot. I think this should be controlled globally with an engine setting. Is that OK?

**Comment by helios2000** [comment]
Yea should be OK. But keep the possibility around to switch between hardware and animated cursors on runtime. Otherwise, people will not understand why animated cursors no longer work, if hardware cursor is enabled.
