### ISSUE TITLE
I was not able to compile it from AUR

### ISSUE THREAD

**Issue by CrafterSvK** [fifengine/fifengine#1022]
I was not able to compile it using ArchLinux AUR repository.

**Comment by LinuxDonald** [comment]
.... more details please have you used my pkg file?

**Comment by CrafterSvK** [comment]
`Compilation error:
Scanning dependencies of target _fifechan
[ 99%] Building CXX object CMakeFiles/_fifechan.dir/fifechanPYTHON_wrap.cxx.o
/tmp/yaourt-tmp-dixi/aur-fife/src/fifengine-0.4.1/build/fifechanPYTHON_wrap.cxx: In function 'PyObject* _wrap_MouseListener_mouseWheelMovedRight(PyObject*, PyObject*)':
/tmp/yaourt-tmp-dixi/aur-fife/src/fifengine-0.4.1/build/fifechanPYTHON_wrap.cxx:5114:35: error: 'class fcn::MouseListener' has no member named 'mouseWheelMovedRight'; did you mean 'mouseWheelMovedUp'?
(arg1)-fcn::MouseListener::mouseWheelMovedRight(*arg2);
^~~~~~~~~~~~~~~~~~~~
/tmp/yaourt-tmp-dixi/aur-fife/src/fifengine-0.4.1/build/fifechanPYTHON_wrap.cxx:5116:15: error: 'class fcn::MouseListener' has no member named 'mouseWheelMovedRight'; did you mean 'mouseWheelMovedUp'?
(arg1)-mouseWheelMovedRight(*arg2);
^~~~~~~~~~~~~~~~~~~~
/tmp/yaourt-tmp-dixi/aur-fife/src/fifengine-0.4.1/build/fifechanPYTHON_wrap.cxx: In function 'PyObject* _wrap_MouseListener_mouseWheelMovedLeft(PyObject*, PyObject*)':
/tmp/yaourt-tmp-dixi/aur-fife/src/fifengine-0.4.1/build/fifechanPYTHON_wrap.cxx:5159:35: error: 'class fcn::MouseListener' has no member named 'mouseWheelMovedLeft'; did you mean 'mouseWheelMovedUp'?
(arg1)-fcn::MouseListener::mouseWheelMovedLeft(*arg2);
^~~~~~~~~~~~~~~~~~~
/tmp/yaourt-tmp-dixi/aur-fife/src/fifengine-0.4.1/build/fifechanPYTHON_wrap.cxx:5161:15: error: 'class fcn::MouseListener' has no member named 'mouseWheelMovedLeft'; did you mean 'mouseWheelMovedUp'?
(arg1)-mouseWheelMovedLeft(*arg2);
^~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/_fifechan.dir/build.make:78: CMakeFiles/_fifechan.dir/fifechanPYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/_fifechan.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
== ERROR: A failure occurred in build().
Aborting...
== ERROR: Makepkg was unable to build fife.`

**Comment by LinuxDonald** [comment]
do you use fife or fife-git package? and fifechan or fifechan-git?

**Comment by CrafterSvK** [comment]
fifechan and fife

**Comment by LinuxDonald** [comment]
for me it looks that you have wrong fifechan version.

**Comment by CrafterSvK** [comment]
Is this a right version? "0.1.4-1"

**Comment by LinuxDonald** [comment]
0.1.4 is the right version and have mouseWheelMovedUp funtion

**Comment by LinuxDonald** [comment]
Have you maybe an older version of fifechan installed?

**Comment by CrafterSvK** [comment]
I have that version so I don't know. Just trying fifechan-git package. Will be back in a minute

**Comment by CrafterSvK** [comment]
Doesn't even work with fifechan-git. Same problem. I have latest version

**Comment by CrafterSvK** [comment]
There is "mouseWheelMovedLeft" which is not right it should be up or down i think

**Comment by helios2000** [comment]
No, thats all right.
Look here https://github.com/fifengine/fifengine/blob/master/engine/core/eventchannel/eventmanager.cpp#L336 and here https://github.com/fifengine/fifechan/blob/master/include/fifechan/mouselistener.hpp#L141

I'm pretty sure you mixed versions of fife and fifechan. If you want to use master version then you need master version of both (fife and fifechan). Or if you want to use latest release of fife (0.4.1) then you need last fifechan release (0.1.4).

**Comment by CrafterSvK** [comment]
I installed that lol. I am sure I have 0.4.1 (fife) and 0.1.4 (fifechan)... One guy from AUR comments have same problem as me

**Comment by helios2000** [comment]
The mouse wheel commits are from 26. Jan. and the relase tags from 7.Feb. So it should be included.

**Comment by CrafterSvK** [comment]
I know right. I am just compiling my own versions from latest github so maybe it will work

**Comment by CrafterSvK** [comment]
It works only if I compile it from github. So the problem is AUR configuration maybe.
