### ISSUE TITLE
OPENALSOFT_INCLUDE_DIR not properly defined on FreeBSD

### ISSUE THREAD

**Issue by AndyMender** [fifengine/fifengine#1026]
I'm using FreeBSD (11-RELEASE as of now) as my development platform and I noticed that fifengine no longer rebuilds properly due to the inclusion/change of a cmake variable OPENALSOFT_INCLUDE_DIR. I quickly looked into the cmake/FindOpenALSoft.cmake cmake script and noticed that Darwin is added as a platform, but FreeBSD is not.

The correct path for the OPENALSOFT_INCLUDE_DIR on FreeBSD is: /usr/local/include/AL. Could you possibly add it as an option under the PATHS block into cmake/FindOpenALSoft.cmake cmake?

If not, I'm okay with defining the variable on the command-line :).

**Comment by LinuxDonald** [comment]
I will do it :)
