### ISSUE TITLE
Make FifeClass objects comparable

### ISSUE THREAD

**Issue by Beliaar** [fifengine/fifengine#1027]
Currently objects that have been retrieved through swig at different times are not comparable because swig uses different memory positions to store them. I have been made aware that those classes hjave a unique fife id, though.

I'd like to make that the normal equality testing method from python. This can be done by adding this code to utilbase.i:

	%extend FifeClass {
		bool __eq__(const PyObject *other) { return false; }
		bool __ne__(const PyObject *other) { return true; }
		bool __eq__(FifeClass *other)
		{ 
			if (!other) return false;
			return $self->getFifeId() == other->getFifeId(); 
		}
		bool __ne__(FifeClass *other)
		{ 
			if (!other) return true;
			return $self->getFifeId() != other->getFifeId(); 
		}
		fifeid_t __hash__() { return $self->getFifeId(); }
	}

This also makes all FifeClasses better usable as dictionary keys.
The functions with PyObject are necessary so swig wont raise a TypeError when comparing with none FifeClasses.

@fifengine/developers @prock-fife @vtchill @helios2000 
What do you think about this change?

**Comment by helios2000** [comment]
I think this is a good idea.

**Comment by Niektory** [comment]
Shouldn't it be `if (!other) return true;` in `__ne__()` though?

**Comment by Beliaar** [comment]
Ah, yes, i forgot that there too, gonna change it.
