### ISSUE TITLE
Fife 0.4.2 release

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#1056]
What about an new fife and fifechan release?

@helios2000

**Comment by helios2000** [comment]
Let us fix a few more bugs, especially we need a solution for you widget problems.

**Comment by prock-fife** [comment]
Should we consider planning the list of bugs we want to fix before releasing?  I'm not entirely sure how much has changed since the last release off the top of my head.  To @helios2000's point we should at least fix enough things to make it worth the release.

**Comment by helios2000** [comment]
Have created an 0.4.2 milestone and added all fixed issues since 7. Feb 17 and also a few open issues that should be fixed before we release the next version.

**Comment by LinuxDonald** [comment]
Updateing changelog is needed too.

**Comment by helios2000** [comment]
Sure, we should follow all the [Release Steps](https://github.com/fifengine/fifengine/issues/955)

**Comment by LinuxDonald** [comment]
I will do the new release next weekend.

**Comment by LinuxDonald** [comment]
@jakoch have you something that you want to add to fife/fifechan before we do the release?

**Comment by jakoch** [comment]
No. Are we ok regarding the dependencies (excluding the cegui issue)?

**Comment by LinuxDonald** [comment]
On the dependencies site are not really big changes. Only glee to glew on linux if i remeber it correctly.

**Comment by jakoch** [comment]
We have an issue with OpenAL-Soft on Windows, see https://ci.appveyor.com/project/LinuxDonald/fifengine/build/job/jopsf0wleklvvnwn/messages

**Comment by LinuxDonald** [comment]
Okay its green again. But we have an problem with openal-soft 1.19.2 maybe you could fix this @jakoch ?
On Ubuntu 19.XX it could be an problem than too..

**Comment by jakoch** [comment]
Oh, nice - all CI platforms are green. The issue disappeared. 

OpenAL-Soft v1.19.2, uhm? According to https://openal-soft.org/ that version isn't released, yet.
Latest is v1.19.1, which we use.

**Comment by LinuxDonald** [comment]
Sorry typo. 1.19.1 don't work. Linux version don't know. Because Ubuntu 18.04lts is on 1.18.2

**Comment by LinuxDonald** [comment]
Release will be today. Fifechan 0.1.5 is out.

**Comment by LinuxDonald** [comment]
Done with https://github.com/fifengine/fifengine/commit/ad2f908195a0cd558542028d2dcb7561cb149ad8

**Comment by jakoch** [comment]
Gute Arbeit, Thomas! 

While looking at the changeset one idea came to my mind:
We could export the "FIFE_VERSION_SHORT" from `CMakeLists.txt` into a environment constant
and re-use that in the `appveyor.yml`, so that one doesn't have to edit the version number in so many places.

**Comment by LinuxDonald** [comment]
Nice idea @jakoch :)
