### ISSUE TITLE
Distinguish filtered mouse events

### ISSUE THREAD

**Issue by jmdejong** [fifengine/fifengine#1057]
Using IMouseFilters it is possible to make a mouse event that was consumed by a gui widget fire anyways?
Is there a way to distinguish these mouse events from mouse events that haven't been consumed by gui widgets?

It looks like this is something that `InputEvent.isConsumedByWidgets()` should do, but it doesn't.
I have searched for it setter, `InputEvent.consumedByWidgets()`, but it isn't called anywhere. It also isn't exported to python, so the application can't call it either.
This seems this whole function quite useless.

Should there be a call to `event.consumedByWidgets();` in these lines?
https://github.com/fifengine/fifengine/blob/bd53d8e3cfda733cd7989c7bf269a11e9a58edff/engine/core/eventchannel/eventmanager.cpp#L720-L722

(the same will probably apply to key events too but I didn't check that)

**Comment by helios2000** [comment]
The ConsumedByWidgets stuff is pretty old. The last setter call was removed 2008.
I would prefer to delete all that old stuff but on the other hand your point is valid. I think the MouseFilter itself wasn't a great idea from me. Maybe it would be better to handle that with a setting or a sort of extra/global listeners. I'll think about it.

**Comment by prock-fife** [comment]
I agree with @helios2000 on this one.  The method in which that was implemented wasn't great and there must be a better way to do that.   It would be nice to make it consistent with the rest of the engine as well as between the mouse and keyboard events.

**Comment by helios2000** [comment]
@jmdejong I hope that is okay for you. It should be enough to do it similar
```
class MouseListener(fife.IMouseListener):
	def __init__(self):		
		fife.IMouseListener.__init__(self)
		self.setGlobalListener(True)
```
Then you can make use of the isConsumedByWidgets flag in the listener methods.
