### ISSUE TITLE
Pyhon 3 support on Archlinux

### ISSUE THREAD

**Issue by yhoyhoj** [fifengine/fifengine#1065]
I'm trying to package fife on Archlinux with Python 3 support.
I am using the AUR [package](https://aur.archlinux.org/packages/fife/) made by @LinuxDonald as a base (edited to change dependencies).   
  
This package sets the PYTHON env variable to `python2` but changing that to `python` or `python3` doesn't help. It always tries to install itself into the`python2.7/site-packages/` directory instead of `python3.6`.  
  
What is the correct way to have Python 3 support ?

**Comment by LinuxDonald** [comment]
I will link an new one. But I can't really update it Because I don't have arch linux anymore.

**Comment by LinuxDonald** [comment]
Have you try: https://aur.archlinux.org/packages/fife-git/

Because last stable fife version dont have py3 support.

**Comment by yhoyhoj** [comment]
It works with this one, thanks !
