### ISSUE TITLE
where is it ?

### ISSUE THREAD

**Issue by Nikola-Tesla-Mandici** [fifengine/fifengine#1066]
**where is it ????**

![2018-07-13_13-57-35](https://user-images.githubusercontent.com/36495485/42709194-4e85ed1e-86a5-11e8-94d2-0fcdd5705008.png)
![2018-07-13_14-00-16](https://user-images.githubusercontent.com/36495485/42709195-4fa3732e-86a5-11e8-8102-3415ec2910f4.png)

**Comment by LinuxDonald** [comment]
http://docs.fifengine.net/developer-manual/en/

Hier ist the lastest doc for developers

**Comment by Nikola-Tesla-Mandici** [comment]
> http://docs.fifengine.net/developer-manual/en/
> 
> Hier ist the lastest doc for developers

thanks for the link that works, what I asked was because when I clicked there I had nothing was empty
