### ISSUE TITLE
fifengine needs zlib.dll but dont include it.

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#1071]
fifengine needs zlib.dll but dont include it. https://ci.appveyor.com/api/buildjobs/519uuubyopb45b99/artifacts/libfife-0.4.2.win32.zip

@jakoch do you know maybe an fix?

**Comment by jakoch** [comment]
The zip package includes zlib1.dll: 
`libfife-0.4.2.win32.zip\Python36\Lib\site-packages\fife\zlib1.dll`.

How do you know that fifengine needs the old zlib.dll. 
What's the exact error and where does it come from?

**Comment by LinuxDonald** [comment]
We found out with UH try to run. If the zlib.dll is missing fife cant get loaded. zlib1.dll is not needed but zlib.dll.

https://github.com/unknown-horizons/unknown-horizons/issues/2890

**Comment by Beliaar** [comment]
I had checked _fife.pyd using dependencies (https://github.com/lucasg/Dependencies/) and it showed that it needs zlib.dll and does not use zlib1.dll at all. Also zlib1.dll apparantly is an outdated version, as renaming it just changed the error slightly ("procedure not found" instead of  "module not found")

**Comment by jmdejong** [comment]
zlib.dll is used by libpng16.dll

**Comment by jakoch** [comment]
@jmdejong oh, i forgot about libpng. You're right. 

We build a zlib.dll,  which should be the correct one for distribution:
https://ci.appveyor.com/project/LinuxDonald/fifengine/build/job/dokfkmwyltuwug0v?fullLog=true#L585
And we link against the lib for libpng16.dll and libpng16-16.dll.

Now i'm confused about what the zlib FAQ says about the filename. 😕

**Comment by jakoch** [comment]
The zlib1.dll issue:
1. we use a prebuilt sdl_ttf package, which ships a zlib1.dll for freetype.dll
2. we use a prebuilt sdl_image package, which ships another zlib1.dll for libpng16-16.dll.
The zlib1.dll's from 2 and 3 clash, when installed in a certain order.
The zlib1.dll from sdl_image works with sdl_ttf, but not vice versa.

Sidenote: Which lib needs the old zlib.dll:
We build libpng, that produces libpng16.dll. it depends on zlib.dll, which we also build.
