### ISSUE TITLE
[Documentation] Games/Projects implemented via FIFE

### ISSUE THREAD

**Issue by rubyFeedback** [fifengine/fifengine#1073]
Would it be possible to add a short subsection of games/projects that were implemented via/through FIFE, on the main README?

New folks often don't know which projects have been implemented via FIFE, so I think it may be useful to see if they wish to contribute more to a game rather than an engine (which I think more people may want to contribute to a game, since an engine is a bit more abstract and possibly also harder).

**Comment by LinuxDonald** [comment]
I don't know what project is using fife active. Unknown-horizons is switching from fife to godot and was the only game that I know that use fifengine on public site

**Comment by jakoch** [comment]
There is a small section of projects using FIFE in our docs: http://docs.fifengine.net/user-manual/en/#_games_using_fifengine
