### ISSUE TITLE
Some documentation links are broken

### ISSUE THREAD

**Issue by CH4Code** [fifengine/fifengine#1075]
Hi,
just trying to get started (again) with Fife. Noticed a small error:
Some of the documentation links in readme.md on the repository page are broken. (they point to fiveengine.net instead of ragingreality.com). The documentation is accessible still via "Overview".
![image](https://user-images.githubusercontent.com/16046997/59197783-70796200-8b92-11e9-83d8-c46869e4124d.png)
Cheers

**Comment by prock-fife** [comment]
Thanks for pointing it out!  I've fixed this.
