### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#192]
This issue was reported by **anxs**

A Feature to apply a number of sound effects on emitters such as FadeIn/Out. Perhabs also with use of the openAL EFX-extension.

Allacrost-Code: (have a look at audio_effects)
[https://allacrost.svn.sourceforge.net/svnroot/allacrost/trunk/demo/src/engine/audio/]

**Comment by helios2000** [comment]
Thats is really a complex theme. I'll implement all sorts of possible sound effects from OpenAL EFX and addtitional fade in and out effect. I will also implement filters.
At the end Fife would have 15 sorts of sound effects and 3 sorts of filters.
