### ISSUE TITLE
critter drawing bug (transparent corrupt or missing image)

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#36]
This issue was reported by **skybound**

For example see denbus1.map; roughly in the middle is a street corner with a "stop" sign; two of the yellowish critters flicker - are only draw sometimes.

Furthermore on the same map in lower left corner (entrance, guard in armor and yellow critter, also flickering) there seems to be a drawing problem: critter partially overdrawn by wall.

**Comment by linuxjackto1** [comment]
thanks
