### ISSUE TITLE
Copy pychan widgets/container at runtime (gui templates)

### ISSUE THREAD

**Issue by totycro** [fifengine/fifengine#376]
At unknown-horizons, we have a container, that displays a production line (what this production takes, what it produces), that is specified in an xml file. 
For buildings, that have more than 1 production line, we'll have to copy this template.

I couldn't find a function in the pychan docs, the only workaround i know is to create the whole container at runtime in the python code. This way, a graphic designer without knowledge of python can't modify the gui code, and the general idea of having xml-files is lost.

**Comment by helios2000** [comment]
Should already be fixed.
