### ISSUE TITLE
Update/Create KDevelop project file

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#406]
trendynick has confirmed that the existing KDevelop project file is no longer usable with FIFE.  It needs to be updated or a new one needs to be created.  He tried with both KDevelop versions 3 and 4.

This task is to update/create the KDevelop project file for FIFE.  The project file should be created to work with KDevelop 4.

**Comment by LinuxDonald** [comment]
I remember that cmake support to create Kdevelop files?

**Comment by jakoch** [comment]
This Scons related issue is no longer relevant, due to the move to CMake.
CMake has a generator for Kdevelop, e.g. `cmake . -G KDevelop4`.
