### ISSUE TITLE
Create FIFE Manual

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#436]
This task is to and create a FIFE manual and determine the format it will be delivered in.  All topics are still being determined but should include documentation for the Editor and other tools included with FIFE.  The final topic list will be posted in this ticket.

**Comment by jakoch** [comment]
The manual has it's own repo now: https://github.com/fifengine/fifengine-docs
It's written in Asciidoc, output format is HTML, PDF output is prepared, but disabled.
Closing.
