### ISSUE TITLE
FIFedit support for custom loaders / savers

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#439]
This issue was reported by **chewie**

FIFedit should allow users to define their own loader/saver duo. E.g. Unknown Horizons is using a combination of sqlite db and filesystem to store their maps. Therefore there is an sqlite loader / saver.

One possible implementation would be, that those loaders / savers describe which format they are written for, and FIFedit chooses them automaticly from the plugin directory due to the selected file extension.

Another way would be to write a profile system which would allow content designers to specify how FIFedit should behave (and which plugins are loaded on startup - as well on how panels are arranged etc.)

**Comment by stubb** [comment]
This issue was moved to fifengine/fifengine-editor#14
