### ISSUE TITLE
Create annotations for the core component.

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#44]
This issue was reported by **phoku**

Create API documentation for this component.

Details: Way to many singletons in here:
- TimeManager
- Engine
- InputManager
- SettingsManager

Also some util classes/files:
- Log
- Exception and derived
- Debugutils

All InputManager infrastructure
- InputListener
- InputListenerRaw
- Events

**Comment by linuxjackto1** [comment]
thanks www.movied.org
