### ISSUE TITLE
History bugs and (many) other bugs

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#452]
This issue was reported by **trendy**

Open map and history window:

Place an instance
 * move instance (multiple times)
 * undo once -» an instance appears at first position
 * undo all -» removes this new-old instance, the moved one remains
  * if you replaced something now they have the default instance (black)

Close/Open map
 * move something around
 * undo is only for show

Clicking again in same place repeats the action (maybe only left clicking: '''i'''nsert,'''r'''emove,'''m'''ove), also you can move nothing (default,black) around.

If you resize the window selecting an entry resizes only the entry list to default dimensions(h&v).

Right clicking (i mode) places a history event for every instance, left clicking only for group action.

Moving with right click doesn't leave traces (no event in history).

**Comment by stubb** [comment]
This issue was moved to fifengine/fifengine-editor#13
