### ISSUE TITLE
Placing an instance on top of another then undoing resets the original instances properties

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#459]
In this case I noticed it resets the instances rotation value.  To reproduce the problem[

1) find an instance that has a rotation value other than 0 (beach tiles are a good example)

2) insert a new instance on top of that one

3) undo

You will notice the origial instances rotation value will be reset to 0 and will not look right.

**Comment by stubb** [comment]
This issue was moved to fifengine/fifengine-editor#12
