### ISSUE TITLE
Add a "cell editor" plugin to the editor

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#481]
There needs to be a "cell editor" plugin added to the editor to allow the user to view all instances in a cell and modify an instances stack position.  The plugin should be much like the layer editor and will have an interface to move the instance up or down in the stack or delete the instance entirely.

The "object editor" plugin will also have to be modified to reflect this change (i.e. the stackpos will need to be removed)

Also, the cell editor should allow you to launch the object editor by highlighting the instance then clicking on "edit"

**Comment by stubb** [comment]
This issue was moved to fifengine/fifengine-editor#8
