### ISSUE TITLE
Add more functionality to FIFE::SoundManager and get rid of the SoundManager extension

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#485]
Including more functionality like:
- have it's own Update function to be called directly by the engine
- callbacks when sounds have finished being played
- manage the number of sounds being played and limit if required
- should not rely on timers
- ability to apply sound effects to specific emitters
- manage the creation and deletion of emitters
- manage OpenAL sources

**Comment by helios2000** [comment]
Apart from the sound effects, I have implemented all the points.
