### ISSUE TITLE
Pychan dropdown menus crash FIFE-based client on win32

### ISSUE THREAD

**Issue by mvbarracuda** [fifengine/fifengine#508]
== FIFE version number ==
Trunk. Not sure when the problem was introduced but it used to work fine with former FIFE versions. Built FIFE from source with either mingw or MSVC 2008 (can be reproduced with both compilers)

== Platform and OS ==
Win7 x64, ActivePython 2.7.0.2 (32bit).

Other PARPG devs couldn't reproduce the bug on their Linux systems, so it's either a win32 only problem or it simply shows up just on a few systems. A developer who could reproduce the bug on a Linux system might get a better backtrace than I get on win32. This bug can be reproduced on my desktop system and my notebook, both running win7 x64.

== How to reproduce ==
- Update FIFE and PARPG (http://parpg-svn.cvsdude.com/parpg/trunk/game/) to latest trunk revision (rev 674)
- Build FIFE on win32 with either mingw or MSVC 2008
- Start PARPG by running run.py
- Choose "New game"
- Press ESC and select "Options" in the menu that pops up
- Try to click on any of the dropdown lists in the menu, all of them will crash PARPG

Unfortunately I couldn't reproduce the behaviour with Rio de hola or any other FIFE demo, but as we didn't change any of our menu code lately, I think this bug is caused by a change to FIFE itself.

== Expected result ==
Dropdown list should be shown when you click on it.

== Actual result ==
Python crashes with an unexpected error. FIFE spits out "terminate called after throwing an instance of 'gcn::Exception'. This points towards guichan / pychan.

== Notes ==
The bug doesn't depend on the used renderer; I could reproduce it for SDL & OpenGL.

I remembered that the UH devs faced similar issues with guichan in the past and decided to remove all dropdown lists in favour of other widget elements. It looks like they didnd't file a ticket for it at the FIFE trac, at least I couldn't find one. That's why I created a new one.

I couldn't get a backtrace with gdb when building FIFE with mingw, it simply says: "Program exited with code 03." And using bt/where after that simply spits out: "No stack".

However I could get a backtrace with the MSVC 2008 debugger. I'm not sure what's the top of the stack and what's the bottom, but it should help to get an idea what's the problem:

```
    _fife.pyd!FIFE::GLImage::setClipArea(const FIFE::RectType<int> & cliparea={...}, bool clear=true)  Line 244 C++ (glimage.cpp)
    _fife.pyd!FIFE::Image::clearClipArea()  Line 173    C++ (image.cpp)
    _fife.pyd!FIFE::Image::popClipArea()  Line 157  C++ (image.cpp)
    _fife.pyd!FIFE::RenderBackend::popClipArea()  Line 65   C++ (renderbackend.cpp)
```

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/2c661d4cf2d7ce738af266c0cae480bed66460d0
