### ISSUE TITLE
Borders are not rendered on edges of widgets that touch their parent container's edge.

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#522]
This issue was reported by **Technomage**

== Description ==
Currently widgets with border_size >= 0 inside a container widget do not render any border edges which touch an edge of the parent container.

== Workaround ==
Add one or more Spacers with fixed_size >= 1 between the child widget and its container's edges.

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/2c661d4cf2d7ce738af266c0cae480bed66460d0
