### ISSUE TITLE
Uninstaller Doesn't Remove fife Module

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#526]
The windows installer runs setup.py bdist_wininst and runs it. However, the uninstaller doesn't then call the bdist's uninstaller. As such, while the main FIFE program gets removed from %PROGRAMFILES%, the fife module doesn't get removed. 

While it would be convenient to have the uninstaller call the python module's uninstaller, it may suffice just to mention that the modules are still installed during the uninstall procedure.

**Comment by LinuxDonald** [comment]
Should be fixed with the next SDK release because new installer is used.

**Comment by jakoch** [comment]
Issue transferred to fife-sdk repo: https://github.com/fifengine/fife-windows-sdk/issues/7
