### ISSUE TITLE
Improve build system shared library support on linux

### ISSUE THREAD

**Issue by vtchill** [fifengine/fifengine#575]
Currently the shared library support in our SCons scripts will generate a shared library but it does not fill out the soname correctly and it does not generate the shared library filename based on version. Our build scripts also do not allow for overriding the shared library install location.

So the following things need to happen to make it easier to create packages of fife for linux distros:
- Fill out soname in generated shared library (should be something like libfife.so.majorVersion)
- Name the generated shared library properly based on fife version (should be something like libfife.so.major.minor.release)
- Allow a new command line option to specify lib install and lookup location

**Comment by LinuxDonald** [comment]
Is that maybe now fixed with the new cmake build system?

**Comment by LinuxDonald** [comment]
@jakoch is that maybe fixed with cmake now?

**Comment by jakoch** [comment]
- we can override the shared library install location ✔️ 
- the shared library filename gets a version stamp ✔️ 
  - but not sure, if file name format is correct: do we have a `libfife.so.major.minor.release` name?

**Comment by LinuxDonald** [comment]
[linuxdonald@linuxdonald-pc lib]$ dir
libfife.so  libfife.so.0  python2.7
[linuxdonald@linuxdonald-pc lib]$
