### ISSUE TITLE
Editor file dialog uses botched relative paths

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#616]
This issue was reported by **Fabian Streitel <fife@rottenrei.be>**

When opening/saving a file in the editor, it does two things that are surprising/broken:

1. it mixes a bunch of directories together (all that are registered with VFS as root directories), which is weird if you register more than one (which we do at UH)
2. it assumes all of these paths are relative to `./..`, which is obviously not the case for directories that are relative to, e.g. the UH root directory.

I modified the code to always use absolute paths, which was a) easy to do and b) fixes both of these problems. See the attached patch, which is relative to the trunk.

**Comment by stubb** [comment]
This issue was moved to fifengine/fifengine-editor#7
