### ISSUE TITLE
Box widgets should contain information about the on-screen positioning (not only relative to parent widget)

### ISSUE THREAD

**Issue by ChrisOelmueller** [fifengine/fifengine#634]
Right now, all widgets added to a VBox/HBox know little about their absolute positioning.
This is sad since we'd like to poll the position of certain widgets and place other widgets depending on where they are located right now.

As a simple check, I added this to dynamic.py#addLabel of the pychan demo and clicked it a few times:

print label.position, label.x, label.y

=>

'''(0, 0), 0, 0'''
---- action
Attach: <fife.extensions.pychan.events._ActionEventListener; proxy of <Swig Object of type 'gcn::ActionListener *' at 0xb4c76098> >
'''(0, 0), 0, 0'''
---- action
Attach: <fife.extensions.pychan.events._ActionEventListener; proxy of <Swig Object of type 'gcn::ActionListener *' at 0xb4c76170> >
'''(0, 0), 0, 0'''

I'd expect those zeros to be something meaningful instead (like 400,210 for the first, 400,230 for the second label

Should this be too hard to implement, one might instead provide another few attributes like real_x, real_y that holds the absolute positioning.

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/2c661d4cf2d7ce738af266c0cae480bed66460d0
