### ISSUE TITLE
adjustSize() sometimes sets width to invalid values

### ISSUE THREAD

**Issue by totycro** [fifengine/fifengine#666]
The setup is as follows:

A Label with a min and max width, which are the same.
It gets some wrapped text, on `resizeToContent`, `ClickLabel::adjustSize` is called[1](../tree/master/engine/core/gui/guichan/widgets/clicklabel.cpp).
Here, `setWidth()` is called with the result of `mGuiFont->getAsImageMultiline(mWrappedText)`, which is `FontBase::getAsImageMultiline`[2](../tree/master/engine/core/video/fonts/fontbase.cpp).
This calculates a width of the text, which i don't yet know what it is.

However this width is set, violating the min/max constraints (first bug). The text is then rewrapped using `wrapText()` in `setWidth()`. After that, the height is set, but with the value from the original image, which has been calculated with the old width. Sometimes the rewrapping requires a new line, which would increase the height, but still the old value is set without rechecking. Therefore the last wrapped part is hidden (second bug).

So the width should not be changed in the first place in this case, and if it would be set in other cases, the height should adapt accordingly, or, the image returned by `getAsImageMultiline` should be such that it's wide enough to fit the maximum line of the original render, such that it decreases the width only so far that the height can stay the same (no additional newlines are introduced).

**Comment by LinuxDonald** [comment]
@helios2000 is that fixed in pychan port?

Found it here at UH: https://github.com/unknown-horizons/unknown-horizons/blob/master/content/gui/xml/ingame/hud/resource_overview_bar_stats.xml

**Comment by helios2000** [comment]
Yea it should. The min, max sizes are now part of Fifechan.

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/2c661d4cf2d7ce738af266c0cae480bed66460d0
