### ISSUE TITLE
Documentation for the various coordinate systems that FIFE uses

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#672]
FIFE uses several different coordinate systems that should be describes somewhere in the documentation in detail.  Please include some real life examples or pseudocode would be great.  Define LayerCoordinates, ScreenCoordinates, ModelCoordinates (and how they relate to mapCoordinates), Exact Coordinates,  etc etc.

**Comment by jakoch** [comment]
Issue transferred to the manual repo.
