### ISSUE TITLE
Create FIFE Icons

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#679]
We need a set of standard icons that will be used for the windows start menu icons as well as icons used in the demos.  Please use the logo in <fife>/docs/logo to start with.

**Comment by LinuxDonald** [comment]
@ChrisOelmueller do oyu know what icons must be done? Maybe Jana Weigel could make them.

**Comment by ChrisOelmueller** [comment]
I don't, sorry.

**Comment by prock-fife** [comment]
We are looking for icons that can be used in the start menu (and perhaps explorer view) on Windows (or perhaps other OS') to pretty things up a bit.  An icon for each of the demos would be nice as well as the editor.    This is really just a nice to have.

**Comment by prock-fife** [comment]
I believe Chris may have already committed an icon though in svn (when we were still using svn) commit 4055.

**Comment by LinuxDonald** [comment]
All icons are needed than?

**Comment by LinuxDonald** [comment]
Are the icons allready implemanted? I could ask janexx from UH if she could render the icons you need?

@prock-fife
