### ISSUE TITLE
ObjectEdit needs to be split up

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#685]
This issue was reported by **chewie**

The ObjectEdit plugin is too bloated ATM. It should be split up into several minor plugins like:

  - highlight selected instance(s)
  - animation viewer
  - instance editor (e.g. instance id; NOTE: most of instance properties have to be stored / organised by the clients game data structure, so we only provide a mini plugin here)
  - object editor (e.g. blocking properties)

**Comment by stubb** [comment]
This issue was moved to fifengine/fifengine-editor#5
