### ISSUE TITLE
ObjectSelector rewrite

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#686]
This issue was reported by **chewie**

This plugin needs a refactoring; it is slow implementation-wise and should be more flexible.

Other issues which should be taken into consideration:
  - vertical / horizontal modes to e.g. make it possible to use the bottom / top dockareas as well (not possible right now as you won't see most of the plugins gui)
  - scroll position when you select an object namespace should be removed as it is annoying instead of helpful
  - preview should be only enabled in text-mode (no need to display the same image twice)
  - image-mode should highlight the current active selection

**Comment by stubb** [comment]
This issue was moved to fifengine/fifengine-editor#4
