### ISSUE TITLE
Spacers don't expand to the dedicated maximum space

### ISSUE THREAD

**Issue by totycro** [fifengine/fifengine#706]
In this example, the spacer should take space until the HBox has a width of 200, but it only goes as far as the Icon's and the Label's combined, i.e. it does not fulfill its purpose.

```
<VBox min_size="200,0" size="200,0" max_size="200,20000" >
  <HBox padding="0" >
    <Icon image="content/gui/images/resbar_stats/gold_icon.png"/>
    <Spacer/>
    <Label name="gold_stats_value" text="+343" />
  </HBox>
</VBox>
```

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/2c661d4cf2d7ce738af266c0cae480bed66460d0
