### ISSUE TITLE
New pychan attributes: ListAttr, ImageAttr

### ISSUE THREAD

**Issue by ChrisOelmueller** [fifengine/fifengine#761]
When defining custom widgets, one sometimes wants to add attributes that serve a certain purpose.
Some of those are already available in `pychan.attrs` -- even specialized ones like `PointAttr` -- but there could always be more of course.

In particular, for UH we add image attributes by using a regular `(Unicode)Attr` and then overwriting the setter with a check like

```
try:
    Icon(image=image)
except RuntimeError:
    # handle default image case here for instance
```

An attribute that can check for whether the path passed is suitable as image (similar to e.g. `Icon.image`, `ImageButton.up/down/hover_image`) would help here.

As for `ListAttr`, the xml serializer already has a (somewhat rough) way of handling lists by storing `[1, 2, 3]` as `"1 ; 2 ; 3"`.
Making that functionality available from pychan as well would be a nice thing to do and at least for UH there definitely are use cases where having a list attribute makes sense in custom widgets.

If you have other ideas for new attributes, feel free to add them here!

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/2c661d4cf2d7ce738af266c0cae480bed66460d0
