### ISSUE TITLE
Mouse sensitivity drastically too low on some machines

### ISSUE THREAD

**Issue by ChrisOelmueller** [fifengine/fifengine#785]
A setting for mouse sensitivity was implemented in #487. Since then, we have come across tickets like unknown-horizons/unknown-horizons#2010 which means that the defaults, while working for some (most?) people, definitely are failing for others.
I believe this was one of the reasons why the need for a mouse sensitivity setting came up at all, and if i remember correctly it was also possible to fix this by changing windowed/fullscreen mode.

**Comment by helios2000** [comment]
Issue still there or can it be closed?
