### ISSUE TITLE
The Console should be optional when using fifechan

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#803]
When initializing the FifechanManager it automatically initializes the Console.  This is not always desired as some clients have no desire to use the console.

**Comment by helios2000** [comment]
It's part of the pychan_porting branch. See FifechanManager setConsoleEnabled() and isConsoleEnabled().

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/2c661d4cf2d7ce738af266c0cae480bed66460d0
