### ISSUE TITLE
SDL 2.0 Support

### ISSUE THREAD

**Issue by helios2000** [fifengine/fifengine#818]
The new SDL comes with a lot of new features and improvements, which FIFE could greatly benefit from.

As starting point the migration guide http://wiki.libsdl.org/moin.fcg/MigrationGuide

**Comment by LinuxDonald** [comment]
helios2000 any news here? Can you maybe work again on it?

**Comment by LinuxDonald** [comment]
@stubb can that here get closed?

**Comment by stubb** [comment]
Merged with commit https://github.com/fifengine/fifengine/commit/0f7f954357aa0a4e928d09697e8945f13389a79f
