### ISSUE TITLE
No PERCENT key

### ISSUE THREAD

**Issue by ChrisOelmueller** [fifengine/fifengine#820]
Not available in KeyType, and the UH hotkey keylistener doesn't detect it as key either.
Any reason for this, or an oversight? How can we work around this?
Keyboard is us-intl with some modifications, `%` as shift+5, no numpad, in case this matters.

**Comment by LinuxDonald** [comment]
have we still this bug with sdl2 support?

**Comment by helios2000** [comment]
I fixed that with the SDL 2 branch. It seems you merged it, so the bug is gone.
