### ISSUE TITLE
Create diagram with all pieces of software involved in the fife universe

### ISSUE THREAD

**Issue by stubb** [fifengine/fifengine#821]
Would be great to have something to show around how fife works and what it really is, same as fifechan, pychan etc.

**Comment by jakoch** [comment]
Info:
I've added support for [AsciiDoctor-diagram](http://asciidoctor.org/docs/asciidoctor-diagram/) to the documentation toolchain at https://github.com/fifengine/fifengine-docs

That means that we can now embed ASCII diagrams (in specific formats) directly in the docs.
The rendering of Grahpviz and Ditaa diagram types is supported. Maybe PlantUML is useful, too.
The ASCII diagrams are converted to images on-the-fly and the images are inserted automatically.
