### ISSUE TITLE
Child hide bug

### ISSUE THREAD

**Issue by helios2000** [fifengine/fifengine#844]
In case you have hidden the child and call show on the parent the child will also be shown. The fix is easy but that will break the editor again.

**Comment by prock-fife** [comment]
Was this the blocker for 0.4.0?  Is the editor working properly now?

**Comment by prock-fife** [comment]
As this fixes pychan I am going to close this issue.  The editor has been moved to it's own repository so if there is an issue with show/hide it will need to be reported there.
