### ISSUE TITLE
Swig error: 'Color' is multiply defined in the generated target language module

### ISSUE THREAD

**Issue by akien-mga** [fifengine/fifengine#859]
Hi,

I'm trying to build the current master branch and am faced with this build error:
```
swig -o build/engine/release/swigwrappers/python/fife_wrap.cc -outdir "engine/python/fife" -Ibuild/engine/release/core -Iengine/core -python -c++ -w511 -w473 -w404 engine/swigwrappers/python/fife.i
engine/core/video/video.i:345: Error: 'Color' is multiply defined in the generated target language module.
engine/core/gui/fifechan/lib/widgets.i:45: Error: Previous declaration of 'Color'
```

I build fifengine with:
```
scons . \
      CXXFLAGS='-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIC' \
      --enable-rend-grid \
      --enable-rend-camzone \
      --prefix=/usr \
      --lib-dir=lib64 \
      --python-prefix=/usr/lib64/python2.7/site-packages \
      fife-shared fife-python fife-swig
```

**Comment by akien-mga** [comment]
This is with swig 3.0.2 and gcc 4.9.2 btw.

**Comment by helios2000** [comment]
Maybe that is a swig or gcc bug.
The error looks like swig won't distinguish between the namespaces. The Color class in video.i is part of FIFE and the one in widgets.i of FCN.

**Comment by akien-mga** [comment]
I just tried building against swig 3.0.3 released a few days ago, but I get the same error.

**Comment by stubb** [comment]
Using swig 3.0.3-1, Fife master and fifechan master your build config works for me removing the fife-swig target which only generates the bindings, which is already included in the fife-python target

**Comment by akien-mga** [comment]
I tried without the fife-swig target, but I get the same error. I'm also building fife master with fifechan master (actually version 0.1.2, but it's the same commit as the master tip).

**Comment by stubb** [comment]
Have your tried to clean up the previous build files with:
    rm -rf .sconsign.dblite build/.sconf_temp
and running afterwards
    scons -c

**Comment by akien-mga** [comment]
Yes I always build in a clean environment (in an RPM package actually).

I just gave it a try out of the RPM with a git snapshot and this instruction, and it worked fine:

I'll investigate tomorrow to see if it's the custom CXXFLAGS or something else that causes my problem, I guess there's something wrong in my package script.

**Comment by stubb** [comment]
I tried exactly the same build config as you posted above, also with the compiler flags. Maybe the environment isnt really clean. Thanks for further investigation. I will close this issue. Feel free to add additional infos. Maybe its useful for others!

**Comment by akien-mga** [comment]
Ok the issue was definitely on my side. There was a leftover from previous packaging instructions:
```
# use libdir instead of lib (for 64bit systems)
for l in ./engine/SConscript ./build/linux2-config.py
do
  sed -i "s|'lib'|'%{_lib}'|g" $l
done
```
where %{_lib} is "lib64" on 64bit systems.

Without this bit it builds fine, as to the 64bit library dir, I guess the --lib-dir=lib64 switch is now sufficient, if not I'll come up with a better fix :-)
