### ISSUE TITLE
Broken forum link in README

### ISSUE THREAD

**Issue by gravitystorm** [fifengine/fifengine#863]
In the README section "Feedback" there is a link to http://forums.fifengine.net/index.php?board=5.0 but this doesn't work. I think it should be either

* http://forums.fifengine.net/index.php?board=2.0 ("Framework Development")
* http://forums.fifengine.net/ (since all the boards are quiet, maybe the general page is better)

**Comment by gravitystorm** [comment]
Thanks!

**Comment by helios2000** [comment]
Thank you for reporting this and for the two pull requests!
