### ISSUE TITLE
scons -c && scons error

### ISSUE THREAD

**Issue by acenode** [fifengine/fifengine#870]
Checking for z (using pkg-config)...no
Checking for z (using z-config)... no
Checking for C++ library z... no
Required lib z not found!

__________
$ brew install zlib
$ homebrew/dupes/zlib-1.2.8 already installed

**Comment by LinuxDonald** [comment]
Have you zlib installed?

**Comment by acenode** [comment]
have zlib-1.2.8 already installed. And I found z.pc pointed to a library Name: Guichan. what is this?

**Comment by LinuxDonald** [comment]
have you https://github.com/fifengine/fifechan installed?

**Comment by acenode** [comment]
yes its installed:

/usr/local/lib/libfifechan.0.1.2.dylib

**Comment by LinuxDonald** [comment]
yes- I think guichan is not needed anymore. Fifechan is the own version of guichan for fife.
Maybe remove guichan and try again?

**Comment by acenode** [comment]
The same error when remove z.pc from disk. maybe this file not the point.
will try re-download all source & rebuild. later.  thanks

**Comment by vtchill** [comment]
Please provide more information when submitting a ticket including:
* OS version/type
* Fife version/type
* Also versions and types of any other libraries you are trying to link with.

I noticed you installed zlib with homebrew so I will assume you are using OS X. Homebrew usually provides nice information after installing a library about where it is installed and if it is linked or not. When I installed zlib through homebrew on os x this is what I see:
```
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/zlib/lib
    CPPFLAGS: -I/usr/local/opt/zlib/include
```

The `LDFLAGS` and `CPPFLAGS` are very important here as these paths may not be in the search paths automatically when compiling fife. You will either need to link zlib explicitly (using something like `brew link zlib` or add these paths to scons `LDFLAGS` and `CPPFLAGS`).

**Comment by LinuxDonald** [comment]
Maybe this helps: http://www.unknown-horizons.org/download/sources/s-osx/

**Comment by stubb** [comment]
Since yesterday fifechan is available via homebrew in the games tap https://github.com/Homebrew/homebrew-games/pull/457#issuecomment-165316759

**Comment by vtchill** [comment]
@stubb - I was not aware of this, who submitted the recipe to homebrew?

**Comment by stubb** [comment]
@vtchill I did it myself. Hopefully I can submit guichan, last release of fife and UH too.

**Comment by vtchill** [comment]
@stubb: can you just make sure to let us know (fifengine people) when they are included just as a heads up.

**Comment by stubb** [comment]
@vtchill  sure

**Comment by stubb** [comment]
@acenode have you been able to found the origin your build problem?

**Comment by stubb** [comment]
Please reopen this issue, if its still valid!
