### ISSUE TITLE
Dependency check for swig version 2.* is missing

### ISSUE THREAD

**Issue by stubb** [fifengine/fifengine#871]
Seems like swig 2.* is required to run the fifengine. Compiling works also with swig 3.*. During startup
the client "Unknown Horizons" crashes with swig3 and  runs fine with swig2.

```
ile "/home/kili/Repositories/unknown-horizons/horizons/gui/widgets/minimap.py", line 82, in Minimap
    _dummy_fife_point = fife.Point(0, 0) # use when you quickly need a temporary point
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 5372, in __init__
    self.this.append(this)
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 5352, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Point, name)
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
```

To get swig2 running on a system where usually swig3 is used, and swig2 is NOT usable by the 'swig' command you have to tell fife what the correct command is. The buildsystem scons knows swig by default and assumes the command is 'swig' http://scons.org/doc/0.97/HTML/scons-user/a3414.html#CV-SWIG . Thats the point where we can step in and replace the default variable '$SWIG' into 'swig-2':

```diff
diff --git a/engine/SConscript b/engine/SConscript
index e9348c3..97b8d0a 100644
--- a/engine/SConscript
+++ b/engine/SConscript
@@ -202,7 +202,7 @@ env.Append(BUILDERS = {'CodeblocksProjectWin32': codeblocks_project_builder_win3
 codeblocks_project_builder_linux = Builder(action = builders.generate_codeblocks_project_linux, suffix = '.cbp')
 env.Append(BUILDERS = {'CodeblocksProjectLinux': codeblocks_project_builder_linux})
 
-python_extensions_builder = Builder(action = "$SWIG -o $TARGET ${_SWIGOUTDIR} ${_SWIGINCFLAGS} $SWIGFLAGS $SOURCES")
+python_extensions_builder = Builder(action = "swig-2 -o $TARGET ${_SWIGOUTDIR} ${_SWIGINCFLAGS} $SWIGFLAGS $SOURCES")
 env.Append(BUILDERS = {'PythonExtensions': python_extensions_builder})
 if fifechan:
        fifechan_env.Append(BUILDERS = { 'PythonExtensions': python_extensions_builder})
```

**Comment by LinuxDonald** [comment]
I think swig 3.0.8 have broken something

**Comment by LinuxDonald** [comment]
I have tested it swig 3.0.8 is broken with swig 3.0.7 it works. I will do some tests with tinyxml2.

**Comment by LinuxDonald** [comment]
with tinyxml2 i become this: [linuxdonald@linuxdonald-arch unknown-horizons]$ ./run_uh.py
Failed to use FIFE from <module 'fife' from '/usr/lib/python2.7/site-packages/fife/__init__.py'>
/usr/lib/python2.7/site-packages/fife/_fife.so: undefined symbol: _ZTV13TiXmlDocument
Failed to find and/or load FIFE.
[linuxdonald@linuxdonald-arch unknown-horizons]$

**Comment by LinuxDonald** [comment]
we need to upgrade fife to use tinyxml2 see here why: http://www.grinninglizard.com/tinyxml2/

**Comment by ChrisOelmueller** [comment]
Can't you set `$SWIG` to your preferred swig instead in the build script you're using? That's what I'm doing in the Arch package for `fife-git` now, anyways (it's `swig-2` provided by `swig2` package there).

**Comment by stubb** [comment]
I simply doesn't thought about set $SWIG itself. Good hint!

**Comment by prock-fife** [comment]
From what I can tell there are 2 issues here.  1 is with Swig and the other with tinyxml2.  Do we NEED to update fife to use tinyxml2 at this point?  Perhaps we can start a new Issue to discuss this one.

For the SWIG issue is this a bug with SWIG or did they fix something that inadvertently broke something that we do?

**Comment by Beliaar** [comment]
I have found the problem with swig and it seems to be fixed in the repo but is unreleased:

https://github.com/swig/swig/pull/584
https://github.com/swig/swig/issues/588

Explanation: Swig 3.0.8 changes exception handling, more precisely instead of
`except:`
it uses
`except Exception:`

But Exception points to fife.Exception in the file which, for whatever reason, causes the error.

**Comment by LinuxDonald** [comment]
with swig 3.0.9 that problem will get fixed. The swig devs found the problem allready.
