### ISSUE TITLE
Cannot iterate over results of CellSelectionRenderer.getLocations in Python

### ISSUE THREAD

**Issue by Unit158** [fifengine/fifengine#878]
std::vector<Location> is not wrapped with any logic with SWIG

edit: this is in version 0.3.5

**Comment by prock-fife** [comment]
I'm not aware of any changes that were made that would address this.  Can someone test in master?

**Comment by LinuxDonald** [comment]
@jakoch is that maybe already fixed?

**Comment by jakoch** [comment]
This is about: https://github.com/fifengine/fifengine/blob/ad585a21430136be96b332da712f5d3f31083f0a/engine/core/view/renderers/cellselectionrenderer.i#L38
This needs an iteration test on the Python side.

Referencing also:
https://github.com/fifengine/fifengine/search?utf8=%E2%9C%93&q=getLocations
https://github.com/fifengine/fifengine/search?utf8=%E2%9C%93&q=CellSelectionRenderer.getLocations
