### ISSUE TITLE
Port Atlas Creator to fifechan

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#881]
Should consider doing this to remove Qt dependency.   Some discussion is required but I'm thinking fifechan is the best candidate.  Another option is to write it as a python FIFE client.

**Comment by stubb** [comment]
Porting this application using fifechan seems like a reasonable decision. A python clients sounds like more work. But depends on the coupling between the atlas creation code and the gui.

**Comment by prock-fife** [comment]
I believe there are some functions in the FIFE Python API that would allow someone to create an atlas and save it to disk.  I haven't looked at the code in such a long time though.

Also, should we consider moving the atlas generator to it's own repo?

**Comment by jakoch** [comment]
It's a standalone Qt application. Please move to its own repo.

What's the intention behind rewriting it, when it works?

**Comment by LinuxDonald** [comment]
@prock-fife any update here because move it to an own repo?

**Comment by jakoch** [comment]
The repository was moved. 
Setting a Qt based build toolchain up (with Travis/Appveyor integration) is now a matter on the new repo.
Closing.
