### ISSUE TITLE
compilation fails; missing fifechan/opengl.hpp

### ISSUE THREAD

**Issue by nonchip** [fifengine/fifengine#884]
```
engine/core/gui/fifechan/base/opengl/opengl_gui_graphics.cpp:28:31: fatal error: fifechan/opengl.hpp: No such file or directory
 #include <fifechan/opengl.hpp>
                               ^
compilation terminated.
scons: *** [build/engine/release/core/gui/fifechan/base/opengl/py_opengl_gui_graphics.os] Error 1
scons: building terminated because of errors.

```

(fifechan built&installed from git a minute before)

**Comment by LinuxDonald** [comment]
We need the complete log please

**Comment by nonchip** [comment]
don't see why, as that was the complete log of g++ for that file, but anyway, there you go: https://www.nonchip.de/paste/53

**Comment by LinuxDonald** [comment]
Because the log shows up more errors in the build process

**Comment by nonchip** [comment]
as far as I can grep, it doesn't. only some warnings. nothing that could prevent a header file from being installed. just the fact that it actually isn't ever installed.

**Comment by nonchip** [comment]
except the "error" you mean is the "i forgot sudo" in the first fifechan `make install` call.

**Comment by prock-fife** [comment]
That would have been it...  in your log for installing fifechan:

```
Makefile:66:`` recipe for target 'install' failed
make:`` *** [install] Error 1
```

Closing.  Please re-open if you have any more issues.

**Comment by nonchip** [comment]
@prock-fife if you'd taken the time to read 3 more lines of log, you'd have seen I OF COURSE noted that and called it with sudo -_-

**Comment by nonchip** [comment]
also i can't reopen, so please do.

**Comment by nonchip** [comment]
also note my usage of the term "**first** `make install` call".

**Comment by prock-fife** [comment]
This is an issue with fifechan.  Opening an issue there...https://github.com/fifengine/fifechan/issues/17
