### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#886]
This is similar #191.

Expected benefits

- CMake is used by fifechan and will allow us to use the CMake Module functionality to find fifechan
- CMake is easily configurable on all operating systems
- SCons does not support python 3 (yet)
- SCons is difficult to re-configure for some operating systems
- SCons is not recommended by a lot of packagers
- CMake can build MSVS solution files (currently we have to build MSVS project files using scons code)
- CMake could potentially prevent swig from running every time you build fife (currently a problem with our scons implementation)
- CMake is more widely used

**Comment by Beliaar** [comment]
I'll see if I can make a basic working cmake file.

**Comment by Beliaar** [comment]
Please test, it works on windws with mingw (5.1.0)

**Comment by vtchill** [comment]
Awesome, I'll try and test it this weekend.

**Comment by prock-fife** [comment]
Looks really good.  I have to put all the re-requisites together to test.

**Comment by Beliaar** [comment]
Should be almost complete now. I couldn't get librocket to compile, though. If someone has a working version (that FIFE supports) they are free to add that.

**Comment by stubb** [comment]
Tried librocket 1.2.1 does compile here neither on a linux machine.

**Comment by stubb** [comment]
Nice work @Beliaar

**Comment by LinuxDonald** [comment]
Maybe we should write into the readme that librocket is broken with cmake?

And can that work merged into master?

**Comment by Beliaar** [comment]
Btw, just fyi. I didn't clean the repo from the scons files, not sure if you want to do that before merging.

**Comment by prock-fife** [comment]
I'd say leave the scons files in there.  We'll deprecate scons in the next release and that gives us some time to fully test cmake.  Great job by the way!

**Comment by LinuxDonald** [comment]
@prock-fife can that work now merged into master?
Than we have both system in master scons and cmake :)

**Comment by prock-fife** [comment]
yes I would say this can get merged as the scons stuff should still work and we can work out any issues in master if required.
