### ISSUE TITLE
Unable run shooter demo 

### ISSUE THREAD

**Issue by xeranas** [fifengine/fifengine#890]
After installing FIFE installation (FIFE_0.3.5_installer_win32.exe) I get errors when trying to run sample project 'shooter'.

OS: Windows 10.

```
C:\Program Files (x86)\FIFE\demos\shooter>c:\Python27\python.exe run.py
Using the FIFE python module found here:  c:\Python27\lib\site-packages\fife
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    settings_gui_xml="")
  File "c:\Python27\lib\site-packages\fife\extensions\fife_settings.py", line 144, in __init__
    shutil.copyfile(self._default_settings_file, os.path.join(self._appdata, self._settings_file))
  File "c:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '.\\settings.xml'

C:\Program Files (x86)\FIFE\demos\shooter>
```

**Comment by stubb** [comment]
It seems like you are not allowed to open the settings.xml file. You should check the file permissions of this file.

**Comment by xeranas** [comment]
FIFE should change default installation location for windows (outside of Program Files folder) so users does not need dealt with permissions issues.

I have little knowledge how to fix permissions on Windows so I just moved FIFE to C:/ directory.

**Comment by prock-fife** [comment]
Thanks for following up on your issue @xeranas.  We'll look at moving default install directory outside of Program Files for the next release.
