### ISSUE TITLE
Remove milestone targets from issues

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#891]
See #888 for the start of this discussion.

Here is a snippet:

> Sidenote/off-topic: Adding milestones to issues 
> You have marked a lot of tickets belonging to the 0.4.0 milestone. When closing all the issues is a must (to be done with that milestone), you will probably never get the 0.4.0 release out. If it's not a must, then planning failed once more and you end up re-scheduling all the tickets to the next milestone and then probably again... It's probably the dream of every open source project that things get done this way, but it simply doesn't work out.
> 
> Of course, it's up for discussion and team decision, but i would suggest to stop setting milestones on issues. One harsh way of doing this, is to remove all milestone labels at once, by simply deleting all existing milestones labels. 
> Pro: It frees you from re-scheduling every single issue. You can still name and tag the next release version manually. Also, when note-worthy issues get closed, you update the changelog manually anyways. It won't impact the project in a blocking way. 
> Con: The downside is that you lose a bit of guidance and signalling for the team on what to do next.
> --up for discussion--
> **Reply from Pock**
> 
> > You have marked a lot of tickets belonging to the 0.4.0 milestone. When closing all the issues is a must (to be done with that milestone), you will probably never get the 0.4.0 release out.
> 
> Noted. We have definitely experienced this first hand and appreciate your suggestions to move away from the current model to one without milestones. I will open another issue for discussion.
> 
> > Con: The downside is that you lose a bit of guidance and signalling for the team on what to do next.
> 
> Generally the team works on what they want to work on based on a general understanding of where we want to go. I don't think milestones have been successful in representing this anyway.

**Comment by LinuxDonald** [comment]
I think that we had should issues on milestones but only one that must be really fixed before you can release an new version. Maybe bugs that are introduced buy the lastest release or crash bug fixes. And what we really need is an new release of fife engine an maybe 0.3.6 or 0.3.9 ??

**Comment by LinuxDonald** [comment]
@prock-fife we from unknown-horizons need an new fife and fifechan release for new uh test/rc release.

**Comment by LinuxDonald** [comment]
I think we should do Tag fife version 0.3.6  and fifechan 1.2.1 and than prepare the release for it when all is done when can do it. When we dont do something in the next time UH will become an Problem :(

**Comment by jakoch** [comment]
We'll need one release tag to test the automatic deployment of a tagged release.
Because we might need to redo this step over and over, until the auto deployment is stable
(tag delete, re-push -  check API access and API keys).
The good thing is you have the patch level version range to mess around in: 0.3.5 - 0.3.99.

After that we are good to go with a "real" new release tag: maybe 0.4.0.

> The new version of fife and fifechan will be release maybe before or togehther with UH.

Both libs, libfife and libfifechan need to be released before UH. I'm not sure, if you work against the latest changes, but assume that the project might need some time to pick them up and integrate them.

**Comment by LinuxDonald** [comment]
UH runs fine with fife and fifechan master. I think prock have said to me the next version will be 0.3.9 or 0.4.0.

**Comment by jakoch** [comment]
Hmm, but you work against the prebuild package: `sudo apt-get install python-fife`, see https://github.com/unknown-horizons/unknown-horizons/blob/master/.travis.yml#L18
Is there a branch over at https://github.com/unknown-horizons/unknown-horizons which uses fife master?

**Comment by LinuxDonald** [comment]
The pre-built version is before the cmake switch. But local most off use using fife master

**Comment by jakoch** [comment]
🤕
