### ISSUE TITLE
intel_do_flush_locked failed: No space left on device

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#894]
I found this error on one of our bug reports at UH:

(last line: intel_do_flush_locked failed: No space left on device)

I have google a bit of this and i found this:

http://stackoverflow.com/questions/25325492/opengl-how-to-correctly-load-unload-textures-from-video-memory
http://stackoverflow.com/questions/25269383/opengl-es-1-1-android-does-gl-gldeletetextures-free-video-memory/25278262#25278262

Have fife here an opengel bug?

@prock-fife @vtchill

**Comment by jakoch** [comment]
Please provide steps to reproduce the problem.

**Comment by helios2000** [comment]
Too old. If that happens again, pleas reopen and give us more informations.
