### ISSUE TITLE
Remove librocket

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#895]
What about to remove librocket? Because it dont compiles on linux on windows mac i dont know and i think no project really use it.

@vtchill 
@prock-fife 

What do you think about that?

**Comment by vtchill** [comment]
I think we should leave librocket support in fife for now. It does not affect the build of fife and if the user wants to compile librocket themselves and integrate it into fife then they will be able to. We should be able to merge the fife cmake work without removing librocket support.

**Comment by prock-fife** [comment]
It's an optional lib for now so lets leave it in.  We can leave the interface un-maintained (use at your own risk type thing) and go from there.  If a project decides to use it we can re-visit it if we see fit.

**Comment by jakoch** [comment]
Ok, keeping it as optional dependency. 
I'm adding a cmake finder.
