### ISSUE TITLE
glee

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine#904]
Hey!

Fifeengine ships GLee (GL Easy Extension library) as an internal dependency
- https://github.com/fifengine/fifengine/tree/master/engine/core/ext/glee
- according to [this comment](https://github.com/fifengine/fifengine/commit/1dfebc93c747f8c1e6d568b4c3dfecfe49b0b173) the version is 5.5 
- [x] the dependency is not listed in the wiki
  - please update https://github.com/fifengine/fifengine/wiki/dependencies and add `Glee v5.5` there

But more important the GLee dependency is dead, 
see https://www.opengl.org/sdk/libs/GLee/ and also the official website http://elf-stone.com/glee.php.
That means it's time to move.
- [ ] discuss possible alternatives
  - direct? GL/GLES3 - https://www.khronos.org/registry/OpenGL/api/
  - GLEW (OpenGL Extension Wrangler Library) - http://glew.sourceforge.net/?
  - GLBinding - https://github.com/cginternals/glbinding?
  - GLFW - http://www.glfw.org/ - http://www.glfw.org/docs/latest/
  - GLAD - https://github.com/Dav1dde/glad
- [ ] create issue/ticket to upgrade to X

Regards, Jens

**Comment by prock-fife** [comment]
@jakoch thanks for the excellent summary.  I'm in agreement that we should discuss possible alternatives and don't have any particular preference as to which we select.  To me the deciding factors are:

1. How much effort will it be to convert from GLee to this library?
2. How active is the project supporting the library?
3. What are other projects selecting?  and why?
4. Does the library support all of FIFE's requirements.  e.g. cross platform, packages in all major Linux distributions, etc etc.

**Comment by vtchill** [comment]
GLEW is the other alternative I have heard of to GLEE that takes a similar approach so I think that it makes sense to look into. There may be other libraries providing similar functionality I'm not sure.

**Comment by jakoch** [comment]
> How much effort will it be to convert from GLee to this library?

GLEW and GLAD are pretty much drop-in replacements for GLee.
The conversion effort is low. I would prefer GLAD.

> Does the library support all of FIFE's requirements. e.g. cross platform, packages in all major Linux distributions, etc etc.

Which requirements has FIFE's GL layer? Which requirements have to be met by the lib? 
Because GLAD allows to compose the library by selecting the needed features in a webinterface: http://glad.dav1d.de/ We can get a way with a really thin layer, if we select this feature set carefully.
(Keep this in mind: Support OpenGL ES 2.0 #793)

**Comment by prock-fife** [comment]
Support for OpenGL ES is a must.  I haven't looked at that code in a long time and our expert @helios2000 has been away for a while now so I cannot really comment on your other questions.  I'm not sure how many extensions we really make use of or what version of OGL we really require.  I'd have to dig into it a bit more.

**Comment by helios2000** [comment]
We currently require OpenGL 2.1. From GLEE we use only Framebuffer Object and some Texture stuff, like NPOT.
And as prock said, OpenGL ES is a must :)

**Comment by jakoch** [comment]
Old requirements: 
```
GLEE_ARB_texture_non_power_of_two
GLEE_ARB_texture_compression
GLEE_EXT_framebuffer_object	
GLEE_EXT_texture_filter_anisotropic	
```
Switch to GLEW incoming in branch: https://github.com/fifengine/fifengine/tree/replace-glee-with-glew
