### ISSUE TITLE
build errors on Appveyor using MSVC

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine#905]
Fifengine doesn't compile on Appveyor using MSVC, because of the high number of errors:

- 126 errors: https://ci.appveyor.com/project/jakoch/fifengine/build/dev-a752a37#L4804
- down to 106 errors: https://ci.appveyor.com/project/jakoch/fifengine/build/dev-d9e3e51#L4770
- down to 98 errors: https://ci.appveyor.com/project/jakoch/fifengine/build/160#L4807
- down to 28 errors: https://ci.appveyor.com/project/jakoch/fifengine/build/162#L4855

The issue is a **blocker** for 
 - compilation of fifengine, 
 - deployment of fifengine-VC.zip
 - deployment of dev-kit (#802)

Would you agree on merging PR 906 (with this broken build state on Appveyor, due to the errors) and then fix the errors (so that i can proceed with deployment config stuff in a second PR)?
How do we want to proceed?

**Comment by vtchill** [comment]
I think it would be fine to merge and then fix errors. What do you think @prock-fife?

**Comment by prock-fife** [comment]
I'm okay with merging and fixing later.

**Comment by jakoch** [comment]
It's down to **1** error now: https://ci.appveyor.com/project/jakoch/fifengine/build/dev-2056175#L4824

**Comment by jakoch** [comment]
All errors fixed.
