### ISSUE TITLE
modify setup.py to accept version from outside

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine#908]
I'd like to do the following on the build server:
`python setup.py %APPVEYOR_BUILD_VERSION% bdist_wininst`

where `%APPVEYOR_BUILD_VERSION%` is either `dev-21k3j54h` or `v1.2.3` on the build server.

It would be nice to modify the file setup.py  to accept the version number as argc/argv input.
That would remove the need to modify the file (and the hardcoded version number) before a release.

(Sidenote: I tried to inject the version with `sed`, but failed, because i couldn't figure out how to do the variable expansion before the insert.)

**Comment by vtchill** [comment]
Sounds reasonable to me.

**Comment by jakoch** [comment]
Ok, works:
https://ci.appveyor.com/project/jakoch/fifengine/build/dev-3057375/artifacts
