### ISSUE TITLE
remove cegui (up to 0.7.9)

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine#909]
There are two cegui layers currently:

- cegui - Crazy Eddie\'s gui subsystem - up to 0.7.9 - false
- cegui-0 - Crazy Eddie\'s gui subsystem - from v 0.8.0 upwards - false

I would like to remove/deprecate the old `cegui` stuff (up to 0.7.9) and rename the `cegui-0` to `cegui`.
Is that ok for you?

**Comment by LinuxDonald** [comment]
I think it's okay. Why we should support an old version of cegui.

**Comment by Niektory** [comment]
Fine with me.

**Comment by Beliaar** [comment]
already wrote in chat, but ok with me too.

**Comment by LinuxDonald** [comment]
@jakoch when @Niektory is fine with it it can be removed. He is the only one that we know that he use cegui for his fife project.

**Comment by prock-fife** [comment]
I have no issues with it.

**Comment by jakoch** [comment]
PR merged. Issue resolved.
