### ISSUE TITLE
Error in version.h

### ISSUE THREAD

**Issue by Psirus** [fifengine/fifengine#916]
I was trying to build fifengine, but got this error (sorry for the german):
```
g++ -o build/engine/release/swigwrappers/python/py_fife_wrap.os -c -DPNG_SKIP_SETJMP_CHECK -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -DTIXML_USE_STL -DNDEBUG -D_REENTRANT -DUSE_SYSTEM_TINY_XML -DHAVE_OPENGL -DHAVE_ZIP -DLOG_ENABLED -DFIFE_GIT_HASH=87f93c74 -I/opt/include -I/usr/include/vorbis -I/usr/include/SDL2 -I/usr/include/python2.7 -Iext/install/include -I/usr/include/AL -I/usr/include/libpng16 -Iengine/core build/engine/release/swigwrappers/python/fife_wrap.cc
In file included from engine/core/video/renderbackend.h:45:0,
                 from engine/core/controller/enginesettings.h:35,
                 from engine/core/controller/engine.h:42,
                 from build/engine/release/swigwrappers/python/fife_wrap.cc:6979:
engine/core/video/image.h:30:0: Warnung: »PNG_SKIP_SETJMP_CHECK« redefiniert
 #define PNG_SKIP_SETJMP_CHECK
 
<Kommandozeile>:0:0: Anmerkung: dies ist die Stelle der vorherigen Definition
In file included from build/engine/release/swigwrappers/python/fife_wrap.cc:9455:0:
engine/core/version.h:58:0: Warnung: »FIFE_VERSION« redefiniert
 #define FIFE_VERSION \
 
engine/core/version.h:29:0: Anmerkung: dies ist die Stelle der vorherigen Definition
  #define FIFE_VERSION "0.4.0"
 
engine/core/version.h:129:2: Fehler: #endif ohne #if
 #endif //FIFE_VERSION_H
  ^~~~~
scons: *** [build/engine/release/swigwrappers/python/py_fife_wrap.os] Error 1
scons: building terminated because of errors.
```
After a little investigating, it appears there is a superfluous `#endif` in [line 79 of version.h](https://github.com/fifengine/fifengine/blob/master/engine/core/version.h#L79)

**Comment by Beliaar** [comment]
Hmm, it does seem that way, I wonder why it never came up until now.

**Comment by Beliaar** [comment]
ok, i see why, that line was left in the file with the newest commit while the #if was removed.

**Comment by jakoch** [comment]
Sorry, my fault. I missed to remove the line, https://github.com/fifengine/fifengine/commit/e43ebc87610cf52a8a687fc76dbbdeda7182f152#diff-7ebaf1190bd7913072455e059be498ddL122

Why didn't this cause a build failure on the CI services?

**Comment by Beliaar** [comment]
maybe use-githash is disable there? that would disable the whole block.

**Comment by jakoch** [comment]
Well, in the CMake builds it's `on` by default and i'm not setting it by using an additional parameter.
https://github.com/fifengine/fifengine/blob/c881b25796f0dc7491dd351bc51535d3b926f8eb/CMakeLists.txt#L36

Wait.. there are paramters which i hardcoded, e.g. `-DPNG_SKIP_SETJMP_CHECK`.
The parameters must be coming from Scons.
Yes, it's a Scons build: `scons: building terminated because of errors.`
We should get rid of that stuff as fast as possible and focus on building with CMake only.
