### ISSUE TITLE
cegui widgets not cleared correctly with active map.

### ISSUE THREAD

**Issue by Beliaar** [fifengine/fifengine#919]
The graphics of CEGUI widgets that were resized or hidden will in some cases still be shown if a map is active.

This could be fixed by calling m_renderbackend->clearBackBuffer(); every pump, but I am not sure if that is a good idea, or if there is a better way.

**Comment by prock-fife** [comment]
I think there is a better way to resolve this.  Generally you don't want to clear the entire backbuffer every frame but only want to mark the appropriate pieces as "dirty" so the renderer will know to render only what it needs to.  @helios2000 would be the guy to talk to about this as I haven't looked at the rendering code in a long time.  Might be good to have a look at the push/pop clip area stuff.

**Comment by Beliaar** [comment]
yeah, that is why i created an issue first, to see if there is a better way.

**Comment by LinuxDonald** [comment]
We can revert it when we have an better fix.

**Comment by Beliaar** [comment]
Also the problem is, that @helios2000 has not been seen for some time.

**Comment by helios2000** [comment]
Yea thats very hacky and not good for performance. So it should be revererted ASAP.
Beliar you wrote that it happens only in some cases, which are they?

**Comment by LinuxDonald** [comment]
@helios2000 you are back :-) :-) :-) :-) :-) is it an dream or are you really back?

**Comment by prock-fife** [comment]
@helios2000 is it you?   is it really you?

**Comment by helios2000** [comment]
Yes, it is me :-D
But not really back, I've still a lot of trouble in RL. The last year was one of the worsts in my live. But I'll try to help again.

**Comment by Beliaar** [comment]
@helios2000 i don't really remember the details anymore at this time. It was happening for widgets that overlapped with the outside black areas of the map.

Also: Welcome back.

**Comment by Niektory** [comment]
@helios2000 Great to see you again! I hope this year will be better for you.

**Comment by helios2000** [comment]
Thank you all :)
Yea the issue is a bit strange, because cegui should clean the related clip areas. Problem is that FIFE don't get data from cegui, it only provides an interface to proceed input and surface to cegui.

**Comment by helios2000** [comment]
@Beliaar Could you test it again without the clearBackBuffer call? Maybe some changes like the enableExtraStateSettings fixed the problem already. Otherwise I've no idea what we could do on our side to fix it.

**Comment by Beliaar** [comment]
@helios2000 I will check it if I have time, thanks for mentioning that.
