### ISSUE TITLE
Use python2 on linux with fife-git cmake not works

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#923]
-- Found PythonInterp: /home/linuxdonald/Downloads/fife-git/src/fifengine/build/python2.7 (found version "1.4")
-- Found PythonLibs: /usr/lib/python2.7/config/libpython2.7.so (found version "2.7.12")
CMake Error at CMakeLists.txt:788 (STRING):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
 
 
--     Python install directory is '/fife'.
-- Configuring incomplete, errors occurred!
See also "/home/linuxdonald/Downloads/fife-git/src/fifengine/build/CMakeFiles/CMakeOutput.log".
See also "/home/linuxdonald/Downloads/fife-git/src/fifengine/build/CMakeFiles/CMakeError.log".
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

I found this one: http://stackoverflow.com/questions/21044665/string-regex-replace-need-6-args-but-mingw-cmake-w7

Used command is: cmake  -DPYTHON_EXECUTABLE=python2.7 -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7/config/libpython2.7.so -DCMAKE_INSTALL_PREFIX:PATH=/usr ..

@jakoch could you maybe take an look on this please?

**Comment by jakoch** [comment]
Ok, the regexp is gone.  lease give it a test on "Fedora".  Travis and Appveyor are ✔️.
Using Linux paths on Windows looks crazy, but works:
https://ci.appveyor.com/project/LinuxDonald/fifengine/build/dev-15b558b#L4433

**Comment by jakoch** [comment]
Fixed.
