### ISSUE TITLE
cmake/FindFifeChan.cmake does not find fifechan.hpp

### ISSUE THREAD

**Issue by rndhro** [fifengine/fifengine#938]
I'm on Linux, cmake 3.5. fifechan is installed into a local directory via ```CMAKE_INSTALL_PREFIX``` and the same directory is used as ```CMAKE_FIND_ROOT_PATH``` when compiling fifengine. fifechan installs ```fifechan.hpp``` into ```${CMAKE_INSTALL_PREFIX}/include/fifechan.hpp``` so I'm wondering how 
```cmake
find_path(FIFECHAN_INCLUDE_DIR fifechan/fifechan.hpp)
```
can possibly find that file at all. Additionally, appending "fifechan" to the path found above is strange, because all ```#include```s in the source files already use the correct prefix  "fifechan/[headername].hpp" 

Maybe I'm doing sth wrong here, but for me it only worked after applying the following patch

```patch
diff --git a/cmake/FindFifeChan.cmake b/cmake/FindFifeChan.cmake
index 5ae79e4..e86ee5a 100644
--- a/cmake/FindFifeChan.cmake
+++ b/cmake/FindFifeChan.cmake
@@ -25,12 +25,7 @@ endif(FIFECHAN_INCLUDE_DIR)
 #                       Find FIFECHAN_INCLUDE_DIR                                
 #------------------------------------------------------------------------------
 
-find_path(FIFECHAN_INCLUDE_DIR fifechan/fifechan.hpp)
-
-# append "fifechan" to include_dir, but only if it's not already added
-if(NOT FIFECHAN_INCLUDE_DIR MATCHES "fifechan$")
-    set(FIFECHAN_INCLUDE_DIR ${FIFECHAN_INCLUDE_DIR}/fifechan)
-endif()
+find_path(FIFECHAN_INCLUDE_DIR NAMES fifechan.hpp)
 
 #------------------------------------------------------------------------------
 #                       Find FIFECHAN_LIBRARY                              
```

**Comment by jakoch** [comment]
Thank you for reporting the issue and contributing the patch!

**Comment by jakoch** [comment]
It fixes the Linux, but breaks Windows builds, see
https://ci.appveyor.com/project/LinuxDonald/fifengine/build/dev-2f94585/job/bn301hbnbb3enp4q#L3414

**Comment by rndhro** [comment]
I was expecting a reason behind this, that's why I didn't send a PR ;)

Why is the Windows build installing the fifechan headers into ```fifengine-dependencies\includes\include\fifechan\``` instead of ```fifengine-dependencies\includes\include\```while the library goes into ```fifengine-dependencies\includes\lib```? I think by changing that, it would build for both OS.

**Comment by jakoch** [comment]
I was trying to create a folder structure on Windows, without dangling files in `include` itself and where every dependency has it's own folder inside `include`. 

The overall folder layout should look like this:

- `fifengine-dependencies` with the folders `build` and `includes`
- `fifengine-dependencies\includes\`  folders:

![include](https://cloud.githubusercontent.com/assets/85608/19962767/7de6b0de-a1b9-11e6-9719-7adbf6375208.png)

- `fifengine-dependencies\includes\include` folders:

![include2](https://cloud.githubusercontent.com/assets/85608/19962777/881db20a-a1b9-11e6-8eac-82d6a0616d36.png)

But, you are right, we could install fifechan into `fifengine-dependencies\includes\include`.
We get rid of the duplicate folder name `include\fifechan\fifechan`, `fifechan.hpp` lands in the include folder and the rest of it's headers remain in the folder `fifechan`. Let's try that..

**Comment by rndhro** [comment]
I see your point on having separate directories per dependency. I haven't used Windows/VisualStudio for ages so I can't comment on that. But IMO the (cmake-) way for that would be to install each dependency into its own directory to have a folder structure like
```
fifengine-dependencies
├── fifechan
│    ├── include
│    ├── lib
│    └── ...
├── boost
│    ├── include
│    ├── lib
│    └── ...
...
└── zlib
     ├── include
     ├── lib
     └── ...
```
and provide a list of all these dependency directories to fifengine's cmake via CMAKE_FIND_ROOT_PATH.

**Comment by jakoch** [comment]
I guess, i'm just used to a folder structure with central `\lib` and `\bin` folders. The deployment step is basically copying `\bin`. Maybe comparable to having a central `/usr/lib` folder. 

Your folder structure would work, too. Having a folder for each component is a very clean approach,
but you would need to  traverse the tree to collect the binaries in the deployment step. 

I don't know, if there is a "cmake way" for a dependencies folder layout. 
I think it's not really documented or standardized and i'm curious how other projects handle this. 
If you know a project with a SDK/dependency package and a good layout, please post a link.
I wouldn't hesitate to take a look and draw some inspiration from there - 
also in regard to the unsolved Mac packaging and deployment issues.

**Comment by Beliaar** [comment]
Not sure if it is a good layout, but cegui has a dependency package - which needs to be compiled by the users. It is just a simple layout where the files of all libraries are in the same respective folders, though.

**Comment by jakoch** [comment]
Thanks for the pointer, Beliaar! 
I took a look at the CeGUI CMakeLists.txt and their dependencies layout looks like this:

```
/dependencies/bin
/dependencies/include
/dependencies/lib/dynamic
/dependencies/lib/static
```

They do not  install each dependency into its own directory.
Their layout is similar to our'sm, where you have the top-level folders `bin`, `include`, `lib`.

**Comment by Beliaar** [comment]
yeah, that is what i was saying.

**Comment by jakoch** [comment]
I solved the windows issue by adding `PATH_SUFFIXES fifechan` to `find_path`.
https://ci.appveyor.com/project/LinuxDonald/fifengine/build/dev-8daa72c
Closing.
