### ISSUE TITLE
minimal boost version should be checked

### ISSUE THREAD

**Issue by VladimirKonkov** [fifengine/fifengine#951]
Hi, fifeengine developers.
I can't link fifengine source against boost-1.58, but boost-1.63 version works fine for me.

Should you point minimal boost version required. Should cmake check it?

best Vladimir.

**Comment by LinuxDonald** [comment]
Hello Thank you for the report. Are you using linux? when yes what distro?

**Comment by jakoch** [comment]
Hey Vladimir! 

We use `find_package(Boost 1.33.1 COMPONENTS system filesystem regex)`, see
https://github.com/fifengine/fifengine/blob/master/CMakeLists.txt#L634

 `find_package` should try to find any version above `1.33.1` 
It's basically a minimum version number / non-exact version match.
But i'm not sure, why linking against 1.58 fails in your case. 
We have to create a reproduction case: try it with 1.58 and cmake in verbose mode, to see what's going on and why it fails.

Regards, Jens

**Comment by VladimirKonkov** [comment]
Ubuntu 16.04
Hey, Jens!
error is just trivial, when run 
> ldd -r _fife.so
it reports that can't find any boost library symbols.
boost-1.58 installed from apt package and boost-1.63 builds from source.
A don't try to build boost-1.58 from the source yet.

**Comment by LinuxDonald** [comment]
Have you libboost-dev installed?

**Comment by LinuxDonald** [comment]
Closed no feedback
