### ISSUE TITLE
Owner of fife

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#953]
@prock-fife can i get owner right of fife please?

and we need an forum backup to transfer to th new server.
And the scripts for the website to move too to an new server.
That we have easier access.

**Comment by helios2000** [comment]
I am strictly against it. LinuxDonald knows almost nothing about FIFE. The last few months have made it clear. FIFE is more than just an engine for UH. Most steps go only in one direction and I think it's the wrong direction.

**Comment by LinuxDonald** [comment]
Okay after release 0.4.0 this weekend I will remove my self from the project.

**Comment by LinuxDonald** [comment]
@helios2000 when I add some commits into git that are not okay see me which one and I will revert they.
