### ISSUE TITLE
FIFE run error

### ISSUE THREAD

**Issue by Sirre87** [fifengine/fifengine#956]
Hi!

I just installed Python and FIFE for the first time today.

I seem to have an issue to run any run-files though, as I get the following error message:

![fife run error](https://cloud.githubusercontent.com/assets/25118755/21954831/7431db22-da5d-11e6-9331-ef8ac4da6cb3.png)

I'm quite new to this so I don't know what's wrong. Any help would be appreciated!

Thanks!

Best Regards,
Sirre

**Comment by jakoch** [comment]
Hello Sirre, 

thank you for reporting the issue.

Could you post the steps so that we can reproduce the problem?

How did you get there? What did you download? What did you execute?

For know, i can only say that you are trying to run the `mapeditor`, right?
Which Python version do you use?

Thanks, Jens

**Comment by Sirre87** [comment]
Hi Jens,

Thanks for the fast reply.

Basically, I did this:
- I downloaded the FIFE installer
- I ran the installer, only to realise I needed to install Python
- I went to the python homepage and downloaded the latest version, Python 3.6.0
- I installed Python in the standard location
- I ran FIFE installer again, which now found the Python location
- Installed FIFE on my external harddrive (my internal is almost full) and finished the installation
- Tried to run the run files of the editor, and the demos. Always same error.

That's it.

Thanks!

**Comment by LinuxDonald** [comment]
Remove you python install and test this: https://ci.appveyor.com/api/buildjobs/fejinlrvyc5jfiwy/artifacts/FifeSDK-0.0.89-Setup-VC14-x86.exe

Dont USE PYTHON3. Editor and demos diont support it yet.

**Comment by jakoch** [comment]
Thank you for describing the steps! 

To explain, why you get the syntax error:
The `mapeditor` needs Python 2.7. It doesn't work with Python3, yet. We are working Py3 support.

**Comment by Sirre87** [comment]
Hi!

Oh, that explains it! I didn't realise there were two different active version of Python!

Installing Python 2.7 solved it, as you said. 

Thank you very much!

**Comment by jakoch** [comment]
Glad we could help. Thanks for trying out fife !! :)
