### ISSUE TITLE
Error when running fife!

### ISSUE THREAD

**Issue by Devix167** [fifengine/fifengine#959]
I ran the engine in 
C:\Program Files (x86)\FIFE\tools\editor\run
and i get this error
http://prntscr.com/dw2j83
Please fix it or help me!
I've looked for this error but havent found it in the issues thing.

**Comment by LinuxDonald** [comment]
Hello what version of fife you are using?

**Comment by Devix167** [comment]
0.3.5

**Comment by LinuxDonald** [comment]
We will release tomorrow version 0.4.0 of fife please test the editor then again on this version. And report if your problem maybe got fixed.

**Comment by Devix167** [comment]
Thanks, ill get it tomorrow.

**Comment by Devix167** [comment]
I see that fife 4.0 is on the releases but how do I download it?

**Comment by LinuxDonald** [comment]
The sdk for easy install will be released in the next hours.

**Comment by Devix167** [comment]
Ok thanks!

**Comment by LinuxDonald** [comment]
https://github.com/fifengine/fife-windows-sdk/releases

SDK is out :)

**Comment by prock-fife** [comment]
Python installer is here:  https://github.com/fifengine/fifengine/files/707089/libfife-0.4.0.win32-py2.7.zip

make sure you remove 0.3.5 before you install this.  Not sure if there is an easy way to uninstall though :(

Latest editor (needs to be release yet) is here: https://github.com/fifengine/fifengine-editor

Just download a zip and extract it somewhere.   that *should* work.

**Comment by LinuxDonald** [comment]
@prock-fife the an version of the editor is in the sdk :)

**Comment by Devix167** [comment]
Okay so I got fife installed and everything from the link @LinuxDonald sent but how do I run the engine?

**Comment by LinuxDonald** [comment]
Do you want to start the editor or own code?

**Comment by Devix167** [comment]
The editor.

**Comment by LinuxDonald** [comment]
the editor should be in the fifesdk folder

**Comment by LinuxDonald** [comment]
double click the run.py file

**Comment by Devix167** [comment]
there is no run.py file.
http://prntscr.com/dweyli

**Comment by LinuxDonald** [comment]
in the mapeditor folder

**Comment by Devix167** [comment]
Im such a noob! sorry XD

but when a ran it a command prompt appeared then disappeared and then nothing happened!

**Comment by LinuxDonald** [comment]
I´m an noob too :P

Rightclick of the run.py and select open with. Choose pythonw.exe in C:\fife\python\pythonw.exe

**Comment by Devix167** [comment]
I ran it with pythonw and nothing happened.

**Comment by LinuxDonald** [comment]
open cmd.exe

and to this:

cd C:\fife\mapeditor
run.py

and give me the log

**Comment by Devix167** [comment]
http://prntscr.com/dwfcq4

**Comment by LinuxDonald** [comment]
@Devix167 thx for the log i will ask an dev for help.

**Comment by prock-fife** [comment]
I think I know the issue.  You may have to delete the auto generated settings.xml file.  I believe it will be located in your user home directory under AppData/FIFE/editor or something to that matter.   Once you have done that re-try running the editor, it should re-create the file and work.

**Comment by Devix167** [comment]
Ok ill try that. Thank you!

**Comment by Devix167** [comment]
Theres no FIFE in appdata. did you mean "AppData/Roaming"?

**Comment by LinuxDonald** [comment]
for me the settings file is in: C:\Users\linux\AppData\Roaming\fife\editor

**Comment by prock-fife** [comment]
sorry.. try here:  <User>\Application Data\fife

**Comment by LinuxDonald** [comment]
remove settings file in: C:\Users\Username\AppData\Roaming\fife\

**Comment by Devix167** [comment]
Ok so i deleted the settings file. Do i run it with normal python or pythonw?

**Comment by LinuxDonald** [comment]
pythonw

**Comment by Devix167** [comment]
nothing happened.

**Comment by LinuxDonald** [comment]
open cmd.exe

and to this:

cd C:\fife\mapeditor
run.py

and give me the log

again please

**Comment by Devix167** [comment]
http://prntscr.com/dwfouw

**Comment by LinuxDonald** [comment]
have you removed all settings.xml files? Maybe do an search on your drive

**Comment by Devix167** [comment]
Ill try again with normal python no settings.xml

**Comment by Devix167** [comment]
HOLY CRAP IT WORKED

**Comment by LinuxDonald** [comment]
:)

**Comment by Devix167** [comment]
Welp, thank you all for the help! Ill get to using the engine as soon as I figure out how to use it!

**Comment by LinuxDonald** [comment]
https://github.com/fifengine/fifengine-docs

**Comment by prock-fife** [comment]
I would suggest checking out the tutorials:  https://github.com/fifengine/python-tutorials

Once you have gone through them check out the demos:  https://github.com/fifengine/fifengine-demos
