### ISSUE TITLE
SDL Mouse Wheel events are not handled correctly

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine#964]
After looking through an issue with rio_de_hola I noticed that FIFE doesn't handle these events exactly right.  See the SDL2 documentation here:  https://wiki.libsdl.org/SDL_MouseWheelEvent

In EventManager::fillMouseEvent look here -> https://github.com/fifengine/fifengine/blob/master/engine/core/eventchannel/eventmanager.cpp#L743 

Notice how FIFE treats x and y scrolls as the same thing.  I believe you should be able to scroll up, down AND left and right (maybe we need MOUSE_WHEEL_LEFT/RIGHT as well???).  Also from the documentation FIFE does not take SDL_MOUSEWHEEL_FLIPPED into consideration.  I don't believe we ran into any platform that had issues with this however it is something to note.

**Comment by helios2000** [comment]
Yea the SDL 2 branch was not finished yet. The mouse wheel was one thing where I was not sure if we should add the additional directions. And what effects this should have on the Fifechan widgets.
The SDL_MOUSEWHEEL_FLIPPED did not exist at that time.

**Comment by prock-fife** [comment]
It would be nice to have some widgets scroll left and right.  Some mice have that capability.  I can imagine it being mostly used with horizontal scroll bars.  But there may be other examples that I cannot thing of right now.

Could we remove the X value from the calculation in eventmanager and add SDL_MOUSEWHEEL_FLIPPED to the mix and call this fixed?

As far as adding MOUSE_WHEEL_LEFT/RIGHT that would be an enhancement and could be handled as another issue.

**Comment by Beliaar** [comment]
With those changes I get an error with TDM-GCC and CEGUI enabled:

> E:\projekte\fifengine\engine\core\gui\cegui\base\ceguiinputprocessor.cpp: In member function 'bool FIFE::CEGuiInputProcessor::processMouseInput(SDL_Event&)':
E:\projekte\fifengine\engine\core\gui\cegui\base\ceguiinputprocessor.cpp:154:4: error: jump to case label [-fpermissive]
    default:
    ^
E:\projekte\fifengine\engine\core\gui\cegui\base\ceguiinputprocessor.cpp:145:13: note:   crosses initialization of 'int32_t wheelChange'
     int32_t wheelChange = event.wheel.y;
