### ISSUE TITLE
Function keys don't work in GUI libraries

### ISSUE THREAD

**Issue by Niektory** [fifengine/fifengine#976]
GUI managers only listen to SDL events, and function keys (F1-F12) aren't dispatched as SDL events because of these lines:
https://github.com/fifengine/fifengine/blob/master/engine/core/eventchannel/eventmanager.cpp#L588-L593

After replacing it with `bool dispatchAsSdl = true;` function keys work fine just like other keys. This check should probably be removed, I don't see a reason for it.

**Comment by prock-fife** [comment]
I'm in agreement that we should allow for the F keys to work.  Not sure why this hasn't come up earlier to be honest.  Simply changing that line looks reasonable to me.
