### ISSUE TITLE
consider using GNUInstallDirs

### ISSUE THREAD

**Issue by ignatenkobrain** [fifengine/fifengine#985]
```cmake
  install(TARGETS fife DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
```

Current solution is very unportable, since on Fedora and SUSE it should fo into /usr/lib64, but on debian it should go into /usr/lib/x86_64-gnu-linux.

**Comment by LinuxDonald** [comment]
Have you an idea how to fix this?

**Comment by ignatenkobrain** [comment]
Something like this: https://github.com/openSUSE/libsolv/pull/141/files

**Comment by LinuxDonald** [comment]
@Beliaar could you maybe take an look on it please?
